// 语言仅适用于菜单
// 在面板属性中选择（Shift + Windows 键）：菜单多语言....
// 目前支持英文、简体中文和繁体中文（always.beta 和 SyaoranChang 翻译）

'use strict';

const English = {
	" - Remove from black list (click name): ": " - Remove from black list (click name): ",
	" biography": " biography",
	" first": " first",
	" image file": " image file",
	" main image": " main image",
	" N/A no tags enabled": " N/A no tags enabled",
	" review": " review",
	" to black list: ": " to black list: ",
	" WARNING: last.fm genre whitelist not found or invalid [try force update - needs internet connection]": " WARNING: last.fm genre whitelist not found or invalid [try force update - needs internet connection]",
	": N/A no playlist tracks selected": ": N/A no playlist tracks selected",
	": similar artists...": ": similar artists...",
	": top albums...": ": top albums...",
	"...": "...",
	"+ Add": "+ Add",
	"+ Add to black list: ": "+ Add to black list: ",
	"Activate biography": "Activate biography",
	"Album": "Album",
	"Album History:": "Album History:",
	"album look-up": "album look-up",
	"Album review [allmusic]": "Album review [allmusic]",
	"Album review [last.fm]": "Album review [last.fm]",
	"Album review [wikipedia]": "Album review [wikipedia]",
	"Album Unknown": "Album Unknown",
	"Album view": "Album view",
	"Align with text": "Align with text",
	"Alignment": "Alignment",
	"Alignment horizontal": "Alignment horizontal",
	"Alignment vertical": "Alignment vertical",
	"All tagger settings...": "All tagger settings...",
	"Allmusic": "Allmusic",
	"Allmusic:": "Allmusic:",
	"Allmusic: ": "Allmusic: ",
	"Alt+Click": "Alt+Click",
	"Alt+Middle click": "Alt+Middle click",
	"Amalgamate": "Amalgamate",
	"Artist": "Artist",
	"Artist (single image [fb2k: display])": "Artist (single image [fb2k: display])",
	"Artist History:": "Artist History:",
	"artist look-up": "artist look-up",
	"Artist Unknown": "Artist Unknown",
	"Artist view": "Artist view",
	"Auto": "Auto",
	"Auto cycle": "Auto cycle",
	"Auto cycle items": "Auto cycle items",
	"Auto lock": "Auto lock",
	"Auto-fallback": "Auto-fallback",
	"Back": "Back",
	"Biography [allmusic location]": "Biography [allmusic location]",
	"Biography [allmusic]": "Biography [allmusic]",
	"Biography [last.fm location]": "Biography [last.fm location]",
	"Biography [last.fm]": "Biography [last.fm]",
	"Biography [wikipedia location]": "Biography [wikipedia location]",
	"Biography [wikipedia]": "Biography [wikipedia]",
	"Black list": "Black list",
	"Bottom": "Bottom",
	"Cancel": "Cancel",
	"Centre": "Centre",
	"Click": "Click",
	"composition loaded": "composition loaded",
	"Composition Unknown": "Composition Unknown",
	"Configure...": "Configure...",
	"Cover": "Cover",
	"Create && manage styles": "Create && manage styles",
	"Create new style...": "Create new style...",
	"Cycle above": "Cycle above",
	"Cycle from custom folder [fallback to above]": "Cycle from custom folder [fallback to above]",
	"Cycle from download folder": "Cycle from download folder",
	"Cycle from folder": "Cycle from folder",
	"Delete custom style...": "Delete custom style...",
	"Disc": "Disc",
	"Display": "Display",
	"Double click": "Double click",
	"Export custom style...": "Export custom style...",
	"Filmstrip": "Filmstrip",
	"Follow selected track (playlist)": "Follow selected track (playlist)",
	"Follow selected track: N/A lyrics or nowplaying enabled": "Follow selected track: N/A lyrics or nowplaying enabled",
	"Force update": "Force update",
	"Freestyle": "Freestyle",
	"Front": "Front",
	"Full overlay": "Full overlay",
	"Heading": "Heading",
	"Icon": "Icon",
	"Image": "Image",
	"Image ": "Image ",
	"Image+text": "Image+text",
	"Inactivate": "Inactivate",
	"Last.fm": "Last.fm",
	"Last.fm Top Albums: ": "Last.fm Top Albums: ",
	"Last.fm:": "Last.fm:",
	"Last.fm: ": "Last.fm: ",
	"Layout": "Layout",
	"Left": "Left",
	"Load": "Load",
	"Manual cycle: wheel over button": "Manual cycle: wheel over button",
	"Middle click": "Middle click",
	"Missing data": "Missing data",
	"Mode: ": "Mode: ",
	"More Tags:": "More Tags:",
	"More...": "More...",
	"N/A - no": "N/A - no",
	"N/A - requires last.fm photo. Selected image: ": "N/A - requires last.fm photo. Selected image: ",
	"No black listed images for current artist": "No black listed images for current artist",
	"Open file location": "Open file location",
	"Open last edited": "Open last edited",
	"Options: see console": "Options: see console",
	"Options...": "Options...",
	"Overlay image area": "Overlay image area",
	"Part overlay": "Part overlay",
	"Paste text from clipboard": "Paste text from clipboard",
	"Photo": "Photo",
	"Photos [last.fm]": "Photos [last.fm]",
	"Playlists": "Playlists",
	"Prefer both": "Prefer both",
	"Prefer composition reviews (allmusic && wikipedia)": "Prefer composition reviews (allmusic && wikipedia)",
	"Prefer nowplaying": "Prefer nowplaying",
	"Reload": "Reload",
	"Rename custom style...": "Rename custom style...",
	"Reset album history...": "Reset album history...",
	"Reset artist history...": "Reset artist history...",
	"Reset style...": "Reset style...",
	"Reset to default size...": "Reset to default size...",
	"Reset zoom": "Reset zoom",
	"Review [allmusic location]": "Review [allmusic location]",
	"Review [allmusic]": "Review [allmusic]",
	"Review [last.fm location]": "Review [last.fm location]",
	"Review [last.fm]": "Review [last.fm]",
	"Review [wikipedia location]": "Review [wikipedia location]",
	"Review [wikipedia]": "Review [wikipedia]",
	"Right": "Right",
	"Show album history": "Show album history",
	"Show artist history": "Show artist history",
	"Show more tags (circle button if present)": "Show more tags (circle button if present)",
	"Show similar artists": "Show similar artists",
	"Show top albums": "Show top albums",
	"Show track review options on load menu": "Show track review options on load menu",
	"Similar Artists:": "Similar Artists:",
	"Sources": "Sources",
	"Static": "Static",
	"Summary": "Summary",
	"Summary compact": "Summary compact",
	"Summary expand": "Summary expand",
	"Tag": "Tag",
	"Tag files...": "Tag files...",
	"Tagger": "Tagger",
	"Text": "Text",
	"Top": "Top",
	"track": "track",
	"Track": "Track",
	"tracks": "tracks",
	"Tracks [allmusic]": "Tracks [allmusic]",
	"Tracks [last.fm]": "Tracks [last.fm]",
	"Tracks [wikipedia]": "Tracks [wikipedia]",
	"Type:": "Type:",
	"Undo": "Undo",
	"Wikipedia": "Wikipedia",
	"Write existing file info to tags: ": "Write existing file info to tags: "
}

const simplifiedChinese = {
	" - Remove from black list (click name): ": " - 从黑名单中删除（点击名称）：",
	" biography": " 简介",
	" first": " 首选",
	" image file": " 图像文件",
	" main image": " 主图像",
	" N/A no tags enabled": " 不可用，未启用标签",
	" review": " 评论",
	" to black list: ": "到黑名单：",
	" WARNING: last.fm genre whitelist not found or invalid [try force update - needs internet connection]": " 警告：last.fm 流派白名单未找到或无效 [尝试强制更新 - 需要互联网连接]",
	": N/A no playlist tracks selected": "：不可用，播放列表内未选择音轨",
	": similar artists...": "：相似艺术家...",
	": top albums...": "：热门专辑...",
	"...": "...",
	"+ Add": "+ 添加",
	"+ Add to black list: ": "+ 添加到黑名单：",
	"Activate biography": "激活简介",
	"Album": "专辑",
	"Album History:": "专辑历史记录：",
	"album look-up": "查找专辑",
	"Album review [allmusic]": "专辑评论 [allMusic]",
	"Album review [last.fm]": "专辑评论 [last.fm]",
	"Album review [wikipedia]": "专辑评论 [维基百科]",
	"Album Unknown": "未知专辑",
	"Album view": "专辑视图",
	"Align with text": "对齐文本",
	"Alignment": "对齐方式",
	"Alignment horizontal": "水平对齐",
	"Alignment vertical": "垂直对齐",
	"All tagger settings...": "标签设置...",
	"Allmusic": "Allmusic",
	"Allmusic:": "Allmusic：",
	"Allmusic: ": "Allmusic：",
	"Alt+Click": "Alt+单击",
	"Alt+Middle click": "Alt+中键单击",
	"Amalgamate": "合并",
	"Artist": "艺术家",
	"Artist (single image [fb2k: display])": "艺术家（单张图片 [fb2k>参数选项>显示]）",
	"Artist History:": "艺术家历史记录：",
	"artist look-up": "查找艺术家",
	"Artist Unknown": "未知艺术家",
	"Artist view": "艺术家视图",
	"Auto": "自动",
	"Auto cycle": "自动循环",
	"Auto cycle items": "自动循环项目",
	"Auto lock": "自动锁定",
	"Auto-fallback": "自动回退",
	"Back": "封底",
	"Biography [allmusic location]": "简介 [allMusic 位置]",
	"Biography [allmusic]": "简介 [allmusic]",
	"Biography [last.fm location]": "简介 [last.fm 位置]",
	"Biography [last.fm]": "简介 [last.fm]",
	"Biography [wikipedia location]": "简介 [维基百科位置]",
	"Biography [wikipedia]": "简介 [维基百科]",
	"Black list": "黑名单",
	"Bottom": "下",
	"Cancel": "取消",
	"Centre": "中",
	"Click": "单击",
	"composition loaded": "加载作品",
	"Composition Unknown": "未知作品",
	"Configure...": "配置...",
	"Cover": "封面",
	"Create && manage styles": "创建和管理样式",
	"Create new style...": "创建新样式...",
	"Cycle above": "以上循环",
	"Cycle from custom folder [fallback to above]": "从自定义文件夹循环 [回退到上面]",
	"Cycle from download folder": "从下载文件夹循环",
	"Cycle from folder": "从文件夹循环",
	"Delete custom style...": "删除自定义样式...",
	"Disc": "碟片",
	"Display": "显示",
	"Double click": "双击",
	"Export custom style...": "导出自定义样式...",
	"Filmstrip": "幻灯片",
	"Follow selected track (playlist)": "跟随所选音轨（播放列表）",
	"Follow selected track: N/A lyrics or nowplaying enabled": "跟随所选音轨：歌词或正在播放启用时不可用",
	"Force update": "强制更新",
	"Freestyle": "自由式",
	"Front": "封面",
	"Full overlay": "完全叠加",
	"Heading": "标题",
	"Icon": "图标",
	"Image": "图像",
	"Image ": "图像",
	"Image+text": "图像+文本",
	"Inactivate": "停用",
	"Last.fm": "Last.fm",
	"Last.fm Top Albums: ": "Last.fm 热门专辑：",
	"Last.fm:": "Last.fm：",
	"Last.fm: ": "Last.fm：",
	"Layout": "布局",
	"Left": "左",
	"Load": "加载",
	"Manual cycle: wheel over button": "手动循环：滚动滚轮",
	"Middle click": "中键单击",
	"Missing data": "缺少数据",
	"Mode: ": "模式：",
	"More Tags:": "更多标签：",
	"More...": "更多...",
	"N/A - no": "不可用 - 无",
	"N/A - requires last.fm photo. Selected image: ": "不可用 - 需要 last.fm 照片。所选图像：",
	"No black listed images for current artist": "当前艺术家没有列入黑名单的图像",
	"Open file location": "打开文件位置",
	"Open last edited": "打开上次编辑的项目",
	"Options: see console": "选项：请查看控制台",
	"Options...": "选项...",
	"Overlay image area": "叠加图像区域",
	"Part overlay": "部分叠加",
	"Paste text from clipboard": "从剪贴板粘贴文本",
	"Photo": "照片",
	"Photos [last.fm]": "照片 [last.fm]",
	"Playlists": "播放列表",
	"Prefer both": "首选两个",
	"Prefer composition reviews (allmusic && wikipedia)": "首选作品评论（allmusic 和 维基百科）",
	"Prefer nowplaying": "首选正在播放项",
	"Reload": "重新加载",
	"Rename custom style...": "重命名自定义样式...",
	"Reset album history...": "重置专辑历史记录...",
	"Reset artist history...": "重置艺术家历史记录...",
	"Reset style...": "重置样式...",
	"Reset to default size...": "重置为默认大小...",
	"Reset zoom": "重置缩放",
	"Review [allmusic location]": "评论 [allMusic 位置]",
	"Review [allmusic]": "评论 [allmusic]",
	"Review [last.fm location]": "评论 [last.fm 位置]",
	"Review [last.fm]": "评论 [last.fm]",
	"Review [wikipedia location]": "评论 [维基百科位置]",
	"Review [wikipedia]": "评论 [维基百科]",
	"Right": "右",
	"Show album history": "显示专辑历史记录",
	"Show artist history": "显示艺术家历史记录",
	"Show more tags (circle button if present)": "显示更多标签（如果存在，则为圆圈按钮）",
	"Show similar artists": "显示相似艺术家",
	"Show top albums": "显示热门专辑",
	"Show track review options on load menu": "在加载菜单上显示音轨评论选项",
	"Similar Artists:": "相似艺术家：",
	"Sources": "来源",
	"Static": "静态",
	"Summary": "摘要",
	"Summary compact": "摘要紧凑",
	"Summary expand": "摘要展开",
	"Tag": "标签",
	"Tag files...": "写入文件标签...",
	"Tagger": "标签",
	"Text": "文本",
	"Top": "上",
	"track": "首",
	"Track": "首",
	"tracks": "首",
	"Tracks [allmusic]": "音轨 [allmusic]",
	"Tracks [last.fm]": "音轨 [last.fm]",
	"Tracks [wikipedia]": "音轨 [维基百科]",
	"Type:": "类型：",
	"Undo": "撤消",
	"Wikipedia": "维基百科",
	"Write existing file info to tags: ": "将现有文件信息写入标签："
}

const traditionalChinese = {
	" - Remove from black list (click name): ": " - 從黑名單中刪除（點擊名稱）： ",
	" biography": " 傳記",
	" first": " 第一的",
	" image file": " 圖片檔案",
	" main image": " 主要圖像",
	" N/A no tags enabled": " N/A 未啟用標籤",
	" review": " 評論",
	" to black list: ": " 加入黑名單： ",
	" WARNING: last.fm genre whitelist not found or invalid [try force update - needs internet connection]": " 警告：未找到 last.fm 類型白名單或無效 [嘗試強制更新 - 需要網路連接]",
	": N/A no playlist tracks selected": ": N/A 未選擇播放列表的曲目",
	": similar artists...": "：相似的表演者...",
	": top albums...": "：熱門專輯...",
	"...": "...",
	"+ Add": "+ 增加",
	"+ Add to black list: ": "+ 加入到黑名單： ",
	"Activate biography": "啟用傳記",
	"Album": "專輯",
	"Album History:": "專輯歷史紀錄：",
	"album look-up": "專輯查詢",
	"Album review [allmusic]": "專輯評論 [allmusic]",
	"Album review [last.fm]": "專輯評論 [last.fm]",
	"Album review [wikipedia]": "專輯評論 [維基百科]",
	"Album Unknown": "專輯不詳",
	"Album view": "專輯檢視",
	"Align with text": "與文字對齊",
	"Alignment": "對齊方式",
	"Alignment horizontal": "水平對齊",
	"Alignment vertical": "垂直對齊",
	"All tagger settings...": "所有標籤編輯器設置...",
	"Allmusic": "Allmusic",
	"Allmusic:": "Allmusic：",
	"Allmusic: ": "Allmusic： ",
	"Alt+Click": "Alt+點擊",
	"Alt+Middle click": "Alt+點擊中鍵",
	"Amalgamate": "合併",
	"Artist": "表演者",
	"Artist (single image [fb2k: display])": "表演者（單一圖片 [fb2k: 顯示]）",
	"Artist History:": "表演者歷史紀錄：",
	"artist look-up": "表演者查詢",
	"Artist Unknown": "表演者不詳",
	"Artist view": "表演者檢視",
	"Auto": "自動",
	"Auto cycle": "自動循環",
	"Auto cycle items": "自動循環項目",
	"Auto lock": "自動鎖",
	"Auto-fallback": "自動回退",
	"Back": "後面",
	"Biography [allmusic location]": "傳記 [allmusic 位置]",
	"Biography [allmusic]": "傳記 [allmusic]",
	"Biography [last.fm location]": "傳記 [last.fm 位置]",
	"Biography [last.fm]": "傳記 [last.fm]",
	"Biography [wikipedia location]": "傳記 [維基百科位置]",
	"Biography [wikipedia]": "傳記 [維基百科]",
	"Black list": "黑名單",
	"Bottom": "底部",
	"Cancel": "取消",
	"Centre": "中心",
	"Click": "點擊",
	"composition loaded": "作品載入",
	"Composition Unknown": "作品不詳",
	"Configure...": "設置...",
	"Cover": "封面",
	"Create && manage styles": "建立和管理樣式",
	"Create new style...": "建立新樣式...",
	"Cycle above": "循環以上",
	"Cycle from custom folder [fallback to above]": "從自訂文件夾循環 [自動退回上面]",
	"Cycle from download folder": "從下載資料夾循環",
	"Cycle from folder": "從資料夾循環",
	"Delete custom style...": "刪除自定義的樣式...",
	"Disc": "光碟",
	"Display": "顯示",
	"Double click": "雙擊",
	"Export custom style...": "匯出自定義的樣式...",
	"Filmstrip": "幻燈片",
	"Follow selected track (playlist)": "跟隨選擇的曲目（播放列表）",
	"Follow selected track: N/A lyrics or nowplaying enabled": "跟隨所選曲目：N/A 歌詞或正在播放已啟用",
	"Force update": "強制更新",
	"Freestyle": "自由風格",
	"Front": "前面",
	"Full overlay": "全疊加",
	"Heading": "標題",
	"Icon": "圖示",
	"Image": "圖片",
	"Image ": "圖片 ",
	"Image+text": "圖片+文字",
	"Inactivate": "停用",
	"Last.fm": "Last.fm",
	"Last.fm Top Albums: ": "Last.fm 熱門專輯： ",
	"Last.fm:": "Last.fm：",
	"Last.fm: ": "Last.fm: ",
	"Layout": "佈局",
	"Left": "左側",
	"Load": "載入",
	"Manual cycle: wheel over button": "手動循環: 滑鼠滾輪按鈕",
	"Middle click": "點擊中鍵",
	"Missing data": "缺失數據",
	"Mode: ": "模式：",
	"More Tags:": "更多標籤：",
	"More...": "更多...",
	"N/A - no": "N/A - 無",
	"N/A - requires last.fm photo. Selected image: ": "N/A - 需要 last.fm 照片。 選擇的圖片： ",
	"No black listed images for current artist": "目前的表演者沒有黑名單的圖片",
	"Open file location": "開啟所在資料夾",
	"Open last edited": "開啟上次編輯",
	"Options: see console": "設定： 查看主控台",
	"Options...": "設定...",
	"Overlay image area": "疊加圖像區域",
	"Part overlay": "零件覆蓋",
	"Paste text from clipboard": "從剪貼簿貼上文字",
	"Photo": "照片",
	"Photos [last.fm]": "照片 [last.fm]",
	"Playlists": "播放列表",
	"Prefer both": "兩者都喜歡",
	"Prefer composition reviews (allmusic && wikipedia)": "比較喜歡作品評論（allmusic 和 維基百科）",
	"Prefer nowplaying": "比較喜歡現在播放",
	"Reload": "重新載入",
	"Rename custom style...": "重新命名自定義的樣式...",
	"Reset album history...": "重置專輯歷史紀錄...",
	"Reset artist history...": "重置表演者歷史紀錄...",
	"Reset style...": "重置樣式...",
	"Reset to default size...": "重置為預設大小...",
	"Reset zoom": "重置縮放",
	"Review [allmusic location]": "評論 [allmusic 位置]",
	"Review [allmusic]": "評論 [allmusic]",
	"Review [last.fm location]": "評論 [last.fm 位置]",
	"Review [last.fm]": "評論 [last.fm]",
	"Review [wikipedia location]": "評論 [維基百科位置]",
	"Review [wikipedia]": "評論 [維基百科]",
	"Right": "右側",
	"Show album history": "顯示專輯歷史紀錄",
	"Show artist history": "顯示表演者歷史紀錄",
	"Show more tags (circle button if present)": "顯示更多標籤（如果有圓圈按鈕）",
	"Show similar artists": "顯示相似的表演者",
	"Show top albums": "顯示熱門專輯",
	"Show track review options on load menu": "在載入選單上顯示曲目評論選項",
	"Similar Artists:": "相似的表演者：",
	"Sources": "來源",
	"Static": "靜態",
	"Summary": "摘要",
	"Summary compact": "總結緊湊",
	"Summary expand": "摘要展開",
	"Tag": "標籤",
	"Tag files...": "標籤檔案...",
	"Tagger": "標籤編輯器",
	"Text": "文字",
	"Top": "頂部",
	"track": "曲目",
	"Track": "曲目",
	"tracks": "曲目",
	"Tracks [allmusic]": "曲目 [allmusic]",
	"Tracks [last.fm]": "曲目 [last.fm]",
	"Tracks [wikipedia]": "曲目 [維基百科]",
	"Type:": "類型：",
	"Undo": "還原",
	"Wikipedia": "維基百科",
	"Write existing file info to tags: ": "將現有文件信息寫入標籤："
}

const lg = [English, simplifiedChinese, traditionalChinese][ppt.menuLanguage];